# -*- coding: utf-8 -*-
"""ANÁLISE FATORIAL CONFIRMATÓRIA (AFC).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RPVciaDupofA_bZDTPGcE-nNvEAcQJuW
"""

"""
ANÁLISE FATORIAL CONFIRMATÓRIA (AFC) - MODELO DE SEGUNDA ORDEM
Dissertação de Rafaela - Mensuração de Governança em Cidades Criativas da UNESCO
Programa de Pós-Graduação em Modelagem Computacional e Sistemas

Modelo de Segunda Ordem:
- Governança (2ª ordem) é explicada por:
  - Coordenação (1ª ordem): Q2-Q7
  - Cooperação (1ª ordem): Q8-Q13
  - Colaboração (1ª ordem): Q14-Q19
  - Representação (1ª ordem): Q20-Q25
"""

import pandas as pd
import numpy as np
import warnings
import os
warnings.filterwarnings('ignore')

# ============================================================================
# FUNÇÕES AUXILIARES
# ============================================================================

def calcular_alpha_cronbach_correto(dados):
    """Calcula o Alpha de Cronbach corretamente"""
    k = dados.shape[1]
    if k < 2:
        return 0
    variancias_itens = dados.var(ddof=1)
    soma_variancias = float(variancias_itens.sum())
    soma_itens = dados.sum(axis=1)
    variancia_total = float(soma_itens.var(ddof=1))
    if variancia_total == 0:
        return 0
    alpha = (k / (k - 1)) * (1 - (soma_variancias / variancia_total))
    return float(max(0, min(1, alpha)))

def calcular_ave_cr(dados, cargas):
    """Calcula AVE e CR baseado nas cargas fatoriais"""
    cargas_array = np.array(cargas)
    ave = float(np.mean(cargas_array ** 2))
    cr = float((np.sum(cargas_array) ** 2) / (np.sum(cargas_array) ** 2 + np.sum(1 - cargas_array ** 2)))
    return ave, cr

def calcular_cargas_e_medias(dados_escala, construtos):
    """Calcula cargas fatoriais e médias dos construtos"""
    cargas_por_construto = {}
    medias_construtos = {}

    for construto, questoes in construtos.items():
        if len(questoes) == 0:
            continue
        media_construto = dados_escala[questoes].mean(axis=1)
        medias_construtos[construto] = media_construto

        cargas = []
        for questao in questoes:
            corr = float(dados_escala[questao].corr(media_construto))
            cargas.append(corr)

        cargas_por_construto[construto] = cargas

    return cargas_por_construto, medias_construtos

def calcular_indices_ajuste_segunda_ordem(dados_escala, construtos_1o, medias_construtos_1o, cargas_construtos_1o):
    """
    Calcula índices de ajuste para modelo de segunda ordem
    """
    n = len(dados_escala)
    questoes_todas = list(dados_escala.columns)
    p = len(questoes_todas)

    # Matriz de covariância observada
    cov_observada = dados_escala.cov().values

    # ========== PRIMEIRA ORDEM ==========
    # Cargas de primeira ordem
    nomes_construtos_1o = list(construtos_1o.keys())
    num_construtos_1o = len(nomes_construtos_1o)

    # Matriz de cargas de primeira ordem (questões → construtos 1ª ordem)
    lambda_1o = np.zeros((p, num_construtos_1o))

    for col_idx, construto in enumerate(nomes_construtos_1o):
        questoes = construtos_1o[construto]
        if construto in cargas_construtos_1o:
            cargas = cargas_construtos_1o[construto]

            for questao, carga in zip(questoes, cargas):
                row_idx = questoes_todas.index(questao)
                lambda_1o[row_idx, col_idx] = carga

    # ========== SEGUNDA ORDEM ==========
    # Calcular correlações entre construtos de primeira ordem
    df_medias_1o = pd.DataFrame(medias_construtos_1o)
    phi_1o = df_medias_1o.corr().values

    # Cargas de segunda ordem (construtos 1ª ordem → Governança)
    # Usar as correlações como cargas de segunda ordem
    cargas_segunda_ordem = np.diag(phi_1o).copy()
    cargas_segunda_ordem = np.sqrt(np.abs(cargas_segunda_ordem))

    # Normalizar
    cargas_segunda_ordem = cargas_segunda_ordem / np.max(cargas_segunda_ordem)

    # ========== MATRIZ DE COVARIÂNCIA REPRODUZIDA ==========
    # Σ = Λ₁ × Φ₁ × Λ₁' + Θ
    # Onde:
    # Λ₁ = matriz de cargas de primeira ordem
    # Φ₁ = matriz de covariância dos fatores de primeira ordem
    # Θ = matriz de variâncias de erro

    # Matriz de variâncias de erro de primeira ordem
    theta_1o = np.zeros((p, p))
    for i in range(p):
        questao = questoes_todas[i]
        for construto, questoes in construtos_1o.items():
            if questao in questoes and construto in cargas_construtos_1o:
                cargas = cargas_construtos_1o[construto]
                carga = cargas[questoes.index(questao)]
                theta_1o[i, i] = 1 - (carga ** 2)
                break

    # Calcular matriz de covariância reproduzida
    cov_reproduzida = lambda_1o @ phi_1o @ lambda_1o.T + theta_1o

    # ========== CÁLCULO DE ÍNDICES ==========

    # Resíduos
    residuos = cov_observada - cov_reproduzida

    # Qui-quadrado
    try:
        inv_cov_obs = np.linalg.inv(cov_observada)
        produto = inv_cov_obs @ cov_reproduzida
        chi2_value = n * (np.trace(produto) - np.log(np.linalg.det(produto)) - p)
        chi2_value = float(max(0, chi2_value))
    except:
        chi2_value = float(n * np.sum(residuos ** 2) / np.sum(cov_observada ** 2))

    # Graus de liberdade
    num_cargas_1o = sum(len(questoes) for questoes in construtos_1o.values())
    num_cargas_2o = num_construtos_1o
    num_variancias_fatores_1o = num_construtos_1o
    num_covariancias_fatores_1o = (num_construtos_1o * (num_construtos_1o - 1)) // 2
    num_variancias_erros = p

    num_parametros = num_cargas_1o + num_cargas_2o + num_variancias_fatores_1o + num_covariancias_fatores_1o + num_variancias_erros

    df = (p * (p + 1)) // 2 - num_parametros

    # Índices
    chi2_df = float(chi2_value / df) if df > 0 else 0.0
    rmsea = float(np.sqrt(max(0, (chi2_value - df) / (n * df)))) if df > 0 else 0.0

    # SRMR
    try:
        diag_cov = np.sqrt(np.diag(cov_observada))
        residuos_padronizados = residuos / np.outer(diag_cov, diag_cov)
        indices_upper = np.triu_indices(p, k=1)
        srmr = float(np.sqrt(np.mean(residuos_padronizados[indices_upper] ** 2)))
    except:
        srmr = 0.0

    # Modelo nulo
    corr_obs = np.corrcoef(dados_escala.T)
    chi2_nulo = n * np.sum((corr_obs[np.triu_indices(p, k=1)]) ** 2)
    df_nulo = (p * (p + 1)) // 2 - p

    # CFI
    if (chi2_nulo - df_nulo) > 0:
        cfi = float(1 - max(0, (chi2_value - df)) / max(0.0001, (chi2_nulo - df_nulo)))
        cfi = float(min(1.0, max(0, cfi)))
    else:
        cfi = 1.0

    # TLI
    if df_nulo > 0 and df > 0:
        tli = float(((chi2_nulo / df_nulo) - (chi2_value / df)) / ((chi2_nulo / df_nulo) - 1))
        tli = float(min(1.0, max(0, tli)))
    else:
        tli = 0.0

    # RNI
    rni = float((chi2_nulo - chi2_value) / chi2_nulo) if chi2_nulo > 0 else 0.0
    rni = float(min(1.0, max(0, rni)))

    return {
        'chi2': chi2_value,
        'df': int(df),
        'chi2_df': chi2_df,
        'rmsea': rmsea,
        'srmr': srmr,
        'cfi': cfi,
        'tli': tli,
        'rni': rni,
        'cargas_1o': lambda_1o,
        'cargas_2o': cargas_segunda_ordem,
        'phi_1o': phi_1o
    }

def avaliar_qualidade_modelo(indices):
    """Avalia a qualidade do modelo baseado nos índices"""
    score = 0

    if indices['chi2_df'] < 3.0:
        score += 1
    if indices['rmsea'] < 0.08:
        score += 1
    if indices['srmr'] < 0.08:
        score += 1
    if indices['cfi'] > 0.95:
        score += 1
    if indices['tli'] > 0.95:
        score += 1
    if indices['rni'] > 0.95:
        score += 1

    return score

# ============================================================================
# CARREGAR DADOS
# ============================================================================

# MODIFICAÇÃO: Função de Upload do Google Colab
try:
    from google.colab import files
    print("O botão de upload aparecerá abaixo. Por favor, selecione seu arquivo CSV ou Excel.")
    uploaded = files.upload()

    if not uploaded:
        print("❌ Nenhum arquivo foi selecionado!")
        caminho_dados = "" # Deixado vazio para gerar erro controlado abaixo
    else:
        # Pega o nome do primeiro arquivo enviado
        caminho_dados = next(iter(uploaded))
        print(f"✓ Arquivo recebido: '{caminho_dados}'")

except ImportError:
    # Caso esteja rodando localmente (fora do Colab), tenta achar na pasta
    print("⚠️  Ambiente não é Google Colab. Procurando arquivo localmente...")
    arquivos_csv = [f for f in os.listdir('.') if f.endswith('.csv')]
    caminho_dados = arquivos_csv[0] if arquivos_csv else 'dados.csv'

if not caminho_dados or not os.path.exists(caminho_dados):
    print(f"❌ ERRO CRÍTICO: O arquivo de dados não foi carregado corretamente.")
    # Não usamos exit() no Colab para permitir correções sem reiniciar o runtime

# Leitura do CSV e renomeação das colunas para manter compatibilidade (2 -> Q2)
# Ajuste para ler arquivos Excel caso o usuário mande o xlsx original, ou csv se for csv
if caminho_dados.endswith('.csv'):
    df = pd.read_csv(caminho_dados)
elif caminho_dados.endswith('.xlsx'):
    df = pd.read_excel(caminho_dados)

# Renomeia as colunas numéricas (str) para Q + numero
df.rename(columns={str(i): f'Q{i}' for i in range(2, 26)}, inplace=True)

questoes_todas = [f'Q{i}' for i in range(2, 26)]
dados_escala = df[questoes_todas]

print("="*100)
print("ANÁLISE FATORIAL CONFIRMATÓRIA (AFC) - MODELO DE SEGUNDA ORDEM")
print("Mensuração de Governança em Cidades Criativas da UNESCO")
print("="*100)
print(f"\n✓ Arquivo de dados carregado com sucesso!")
print(f"  Respondentes: {len(df)}")
print(f"  Questões: {len(questoes_todas)}")

# ============================================================================
# DEFINIR MODELO DE SEGUNDA ORDEM
# ============================================================================

print("\n\n" + "="*100)
print("MODELO DE SEGUNDA ORDEM")
print("="*100)

construtos_1o = {
    'Coordenação': ['Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7'],
    'Cooperação': ['Q8', 'Q9', 'Q10', 'Q11', 'Q12', 'Q13'],
    'Colaboração': ['Q14', 'Q15', 'Q16', 'Q17', 'Q18', 'Q19'],
    'Representação': ['Q20', 'Q21', 'Q22', 'Q23', 'Q24', 'Q25']
}

print("\nEstrutura do Modelo:")
print("-" * 100)
print("\nGOVERNANÇA (2ª Ordem)")
for construto, questoes in construtos_1o.items():
    print(f"  └─ {construto} (1ª Ordem): {', '.join(questoes)}")

# ============================================================================
# ANÁLISE DE PRIMEIRA ORDEM
# ============================================================================

print("\n\n" + "="*100)
print("1. ANÁLISE DE PRIMEIRA ORDEM")
print("="*100)

cargas_1o, medias_1o = calcular_cargas_e_medias(dados_escala, construtos_1o)

print("\nCargas Fatoriais de Primeira Ordem:")
print("-" * 100)

for construto, questoes in construtos_1o.items():
    print(f"\n{construto}:")
    if construto in cargas_1o:
        for questao, carga in zip(questoes, cargas_1o[construto]):
            status = "✓" if carga > 0.7 else "!" if carga > 0.5 else "✗"
            print(f"  {questao}: {carga:.4f} {status}")

# ============================================================================
# VALIDADE E CONFIABILIDADE DE PRIMEIRA ORDEM
# ============================================================================

print("\n\n" + "="*100)
print("2. VALIDADE CONVERGENTE E CONFIABILIDADE (1ª ORDEM)")
print("="*100)

resultados_confiabilidade_1o = {}

for construto, questoes in construtos_1o.items():
    if construto not in cargas_1o or len(questoes) == 0:
        continue

    dados_construto = dados_escala[questoes]
    cargas = cargas_1o[construto]

    ave, cr = calcular_ave_cr(dados_construto, cargas)
    alpha = calcular_alpha_cronbach_correto(dados_construto)

    resultados_confiabilidade_1o[construto] = {
        'AVE': ave,
        'CR': cr,
        'Alpha': alpha
    }

    print(f"\n{construto}:")
    print(f"  AVE: {ave:.4f} {'✓' if ave > 0.5 else '✗'}")
    print(f"  CR: {cr:.4f} {'✓' if cr > 0.7 else '✗'}")
    print(f"  Alpha: {alpha:.4f} {'✓' if alpha > 0.7 else '✗'}")

# ============================================================================
# CORRELAÇÕES ENTRE CONSTRUTOS DE PRIMEIRA ORDEM
# ============================================================================

print("\n\n" + "="*100)
print("3. CORRELAÇÕES ENTRE CONSTRUTOS (1ª ORDEM)")
print("="*100)

df_medias_1o = pd.DataFrame(medias_1o)
corr_construtos_1o = df_medias_1o.corr()

print("\nMatriz de Correlação:")
print("-" * 100)
print(corr_construtos_1o.to_string())

# ============================================================================
# VALIDADE DISCRIMINANTE
# ============================================================================

print("\n\n" + "="*100)
print("4. VALIDADE DISCRIMINANTE (Critério de Fornell-Larcker)")
print("="*100)

print("\nCritério: √AVE deve ser maior que a correlação com outros construtos")
print("-" * 100)

for construto in construtos_1o.keys():
    if construto not in resultados_confiabilidade_1o:
        continue

    sqrt_ave = np.sqrt(resultados_confiabilidade_1o[construto]['AVE'])
    print(f"\n{construto} (√AVE = {sqrt_ave:.4f}):")

    for outro_construto in construtos_1o.keys():
        if construto == outro_construto:
            continue

        corr = corr_construtos_1o.loc[construto, outro_construto]
        status = "✓" if sqrt_ave > corr else "✗"
        print(f"  vs {outro_construto}: {corr:.4f} {status}")

# ============================================================================
# ANÁLISE DE SEGUNDA ORDEM
# ============================================================================

print("\n\n" + "="*100)
print("5. ANÁLISE DE SEGUNDA ORDEM")
print("="*100)

print("\nCargas de Segunda Ordem (Construtos 1ª → Governança):")
print("-" * 100)

# Calcular cargas de segunda ordem como correlações com fator geral
media_geral = dados_escala.mean(axis=1)

cargas_2o = {}
for construto, media_1o in medias_1o.items():
    carga = float(media_1o.corr(media_geral))
    cargas_2o[construto] = carga
    status = "✓" if carga > 0.7 else "!" if carga > 0.5 else "✗"
    print(f"{construto}: {carga:.4f} {status}")

# ============================================================================
# ÍNDICES DE AJUSTE GLOBAL
# ============================================================================

print("\n\n" + "="*100)
print("6. ÍNDICES DE AJUSTE GLOBAL DO MODELO")
print("="*100)

indices = calcular_indices_ajuste_segunda_ordem(dados_escala, construtos_1o, medias_1o, cargas_1o)
qualidade = avaliar_qualidade_modelo(indices)

print(f"\nQualidade do Modelo: {qualidade}/6 critérios atendidos")

print(f"\n┌─ ÍNDICES DE AJUSTE ─────────────────────────────────────────────────────────────────────────┐")
print("│                                                                                             │")
print(f"│  Qui-Quadrado (χ²):                  {indices['chi2']:>15.4f}                              │")
print(f"│  Graus de Liberdade (df):            {indices['df']:>15.0f}                              │")
print(f"│  χ²/df:                              {indices['chi2_df']:>15.4f}   {'✓' if indices['chi2_df'] < 3.0 else '✗'}                  │")
print("│                                                                                             │")
print(f"│  RMSEA:                              {indices['rmsea']:>15.4f}   {'✓' if indices['rmsea'] < 0.08 else '✗'}                  │")
print(f"│  SRMR:                               {indices['srmr']:>15.4f}   {'✓' if indices['srmr'] < 0.08 else '✗'}                  │")
print(f"│  CFI:                                {indices['cfi']:>15.4f}   {'✓' if indices['cfi'] > 0.95 else '✗'}                  │")
print(f"│  TLI:                                {indices['tli']:>15.4f}   {'✓' if indices['tli'] > 0.95 else '✗'}                  │")
print(f"│  RNI:                                {indices['rni']:>15.4f}   {'✓' if indices['rni'] > 0.95 else '✗'}                  │")
print("│                                                                                             │")
print("└─────────────────────────────────────────────────────────────────────────────────────────────┘")

# ============================================================================
# RESUMO FINAL
# ============================================================================

print("\n\n" + "="*100)
print("7. RESUMO FINAL")
print("="*100)

print("\nTabela de Indicadores (1ª Ordem):")
print("-" * 100)
print("Construto\t\tAVE\tCR\tAlpha\t√AVE")
print("-" * 100)

for construto in construtos_1o.keys():
    if construto in resultados_confiabilidade_1o:
        r = resultados_confiabilidade_1o[construto]
        sqrt_ave = np.sqrt(r['AVE'])
        print(f"{construto}\t\t{r['AVE']:.4f}\t{r['CR']:.4f}\t{r['Alpha']:.4f}\t{sqrt_ave:.4f}")

print("\n\nCargas de Segunda Ordem:")
print("-" * 100)
for construto, carga in cargas_2o.items():
    status = "✓" if carga > 0.7 else "!" if carga > 0.5 else "✗"
    print(f"{construto}: {carga:.4f} {status}")

print("\n\nCritérios de Adequação:")
print("-" * 100)

criterios = [
    ('χ²/df < 3.0', indices['chi2_df'] < 3.0, indices['chi2_df']),
    ('RMSEA < 0.08', indices['rmsea'] < 0.08, indices['rmsea']),
    ('SRMR < 0.08', indices['srmr'] < 0.08, indices['srmr']),
    ('CFI > 0.95', indices['cfi'] > 0.95, indices['cfi']),
    ('TLI > 0.95', indices['tli'] > 0.95, indices['tli']),
    ('RNI > 0.95', indices['rni'] > 0.95, indices['rni'])
]

for criterio, atendido, valor in criterios:
    status = "✓" if atendido else "✗"
    print(f"{status} {criterio}: {valor:.4f}")

# ============================================================================
# CONCLUSÕES
# ============================================================================

print("\n\n" + "="*100)
print("8. CONCLUSÕES")
print("="*100)

print("\n✓ Validade Convergente (AVE > 0,5): ", end="")
if all(r['AVE'] > 0.5 for r in resultados_confiabilidade_1o.values()):
    print("ATENDIDO")
else:
    print("NÃO ATENDIDO")

print("✓ Confiabilidade (CR > 0,7): ", end="")
if all(r['CR'] > 0.7 for r in resultados_confiabilidade_1o.values()):
    print("ATENDIDO")
else:
    print("NÃO ATENDIDO")

print("✓ Consistência Interna (Alpha > 0,7): ", end="")
if all(r['Alpha'] > 0.7 for r in resultados_confiabilidade_1o.values()):
    print("ATENDIDO")
else:
    print("NÃO ATENDIDO")

print("✓ Validade Discriminante: ", end="")
# Verificar Fornell-Larcker
validade_discriminante = True
for construto in construtos_1o.keys():
    if construto not in resultados_confiabilidade_1o:
        continue
    sqrt_ave = np.sqrt(resultados_confiabilidade_1o[construto]['AVE'])
    for outro_construto in construtos_1o.keys():
        if construto == outro_construto:
            continue
        corr = corr_construtos_1o.loc[construto, outro_construto]
        if sqrt_ave <= corr:
            validade_discriminante = False
            break

if validade_discriminante:
    print("ATENDIDO")
else:
    print("NÃO ATENDIDO")

print(f"\n✓ Índices de Ajuste Global: {qualidade}/6 critérios atendidos")

if qualidade >= 5:
    print("\n🎉 MODELO COM EXCELENTE AJUSTE!")
elif qualidade >= 4:
    print("\n✓ MODELO COM BOM AJUSTE")
elif qualidade >= 3:
    print("\n⚠️  MODELO COM AJUSTE ACEITÁVEL")
else:
    print("\n❌ MODELO COM AJUSTE INADEQUADO")

# ============================================================================
# SALVAR RESULTADOS
# ============================================================================

diretorio_atual = os.getcwd() # Ajuste seguro para Colab
caminho_resultado = os.path.join(diretorio_atual, 'afc_segunda_ordem_resultados.txt')

with open(caminho_resultado, 'w', encoding='utf-8') as f:
    f.write("="*100 + "\n")
    f.write("ANÁLISE FATORIAL CONFIRMATÓRIA - MODELO DE SEGUNDA ORDEM\n")
    f.write("="*100 + "\n\n")

    f.write("ESTRUTURA DO MODELO\n\n")
    f.write("GOVERNANÇA (2ª Ordem)\n")
    for construto, questoes in construtos_1o.items():
        f.write(f"  └─ {construto} (1ª Ordem): {', '.join(questoes)}\n")

    f.write("\n\nÍNDICES DE AJUSTE GLOBAL\n\n")
    f.write(f"Qualidade: {qualidade}/6\n")
    f.write(f"χ²/df: {indices['chi2_df']:.4f}\n")
    f.write(f"RMSEA: {indices['rmsea']:.4f}\n")
    f.write(f"SRMR: {indices['srmr']:.4f}\n")
    f.write(f"CFI: {indices['cfi']:.4f}\n")
    f.write(f"TLI: {indices['tli']:.4f}\n")
    f.write(f"RNI: {indices['rni']:.4f}\n\n")

    f.write("VALIDADE E CONFIABILIDADE (1ª ORDEM)\n\n")
    f.write("Construto\tAVE\tCR\tAlpha\n")
    for construto in construtos_1o.keys():
        if construto in resultados_confiabilidade_1o:
            r = resultados_confiabilidade_1o[construto]
            f.write(f"{construto}\t{r['AVE']:.4f}\t{r['CR']:.4f}\t{r['Alpha']:.4f}\n")

    f.write("\n\nCARGAS DE SEGUNDA ORDEM\n\n")
    for construto, carga in cargas_2o.items():
        f.write(f"{construto}: {carga:.4f}\n")

print(f"\n✓ Resultado salvo em: {caminho_resultado}")

print("\n" + "="*100)
print("ANÁLISE FATORIAL CONFIRMATÓRIA (SEGUNDA ORDEM) CONCLUÍDA")
print("="*100)