# -*- coding: utf-8 -*-
"""Comparação de Índices de Ajuste Global.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ba_Xv16yrzFIPNPAinIei8U0kMTkGLM-
"""

import matplotlib.pyplot as plt
import numpy as np

# 1. Dados extraídos das suas tabelas reais
indices = ['CFI', 'TLI', 'RMSEA', 'SRMR']
unidim = [0.485, 0.412, 0.267, 0.158]
segunda_ordem = [0.615, 0.572, 0.215, 0.124]

x = np.arange(len(indices))  # localização das etiquetas
width = 0.35  # largura das barras

fig, ax = plt.subplots(figsize=(10, 6))

# 2. Criar as barras
rects1 = ax.bar(x - width/2, unidim, width, label='Modelo Unidimensional', color='#d1d1d1')
rects2 = ax.bar(x + width/2, segunda_ordem, width, label='Modelo de Segunda Ordem', color='#2b5b84')

# 3. Adicionar textos e rótulos
ax.set_ylabel('Valores dos Índices')
ax.set_title('Figura 4: Comparação de Índices de Ajuste Global', fontsize=16, pad=20)
ax.set_xticks(x)
ax.set_xticklabels(indices)
ax.legend()

# Adicionar os valores em cima das barras para clareza
ax.bar_label(rects1, padding=3, fmt='%.3f')
ax.bar_label(rects2, padding=3, fmt='%.3f')

# 4. Ajustes finais e salvamento
plt.ylim(0, 0.8) # Limite para dar respiro ao gráfico
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.savefig('comparativo_modelos.png', dpi=300)
plt.show()