# -*- coding: utf-8 -*-
"""Matriz de Correlações entre Construtos (AFC).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14gWjTuSLWKkDlIMGEOQEpvqJKtGooGLP
"""

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# 1. Definir os dados reais da matriz de correlação
data = {
    'Coordenação': [1.00, 0.83, 0.81, 0.78],
    'Cooperação': [0.83, 1.00, 0.86, 0.82],
    'Colaboração': [0.81, 0.86, 1.00, 0.80],
    'Representação': [0.78, 0.82, 0.80, 1.00]
}

df = pd.DataFrame(data, index=['Coordenação', 'Cooperação', 'Colaboração', 'Representação'])

# 2. Configurar o estilo visual
plt.figure(figsize=(10, 8))
sns.set_theme(style="white")

# 3. Criar o heatmap
# Usamos 'Blues' para tons de azul intensos conforme sua descrição
mask = np.triu(np.ones_like(df, dtype=bool)) # Máscara para mostrar apenas metade (opcional)
heatmap = sns.heatmap(df, annot=True, cmap='Blues', fmt=".2f",
                     linewidths=.5, cbar_kws={"shrink": .8}, vmin=0.5)

plt.title('Figura 3: Matriz de Correlações entre Construtos (AFC)', fontsize=16, pad=20)
plt.xticks(rotation=45)
plt.yticks(rotation=0)

# 4. Salvar e mostrar
plt.tight_layout()
plt.savefig('heatmap_correlacoes.png', dpi=300)
plt.show()