# -*- coding: utf-8 -*-
"""Scree Plot - sedimentação.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-EIYOENgHZpjS3KS8Lh8lRXwNuTkD5LO
"""

# ==============================================================================
# 1. INSTALAÇÃO E IMPORTAÇÃO DE BIBLIOTECAS
# ==============================================================================
!pip install factor_analyzer -q  # Instala a biblioteca de análise fatorial

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import io
from google.colab import files
from factor_analyzer import FactorAnalyzer
from factor_analyzer.factor_analyzer import calculate_bartlett_sphericity, calculate_kmo

# ==============================================================================
# 2. CARREGAMENTO DOS DADOS
# ==============================================================================
print("--- POR FAVOR, FAÇA O UPLOAD DO SEU ARQUIVO EXCEL OU CSV ---")
uploaded = files.upload()
filename = next(iter(uploaded))

# Leitura dinâmica (identifica se é Excel ou CSV)
if filename.endswith('.xlsx'):
    df = pd.read_excel(io.BytesIO(uploaded[filename]))
else:
    df = pd.read_csv(io.BytesIO(uploaded[filename]))

# Seleção das colunas de interesse (Questões Q2 a Q25)
# O script assume que as colunas estão nomeadas de '2' a '25'
cols = [str(i) for i in range(2, 26)]
existing_cols = [c for c in cols if c in df.columns]
data = df[existing_cols].dropna()

# ==============================================================================
# 3. TRATAMENTO PARA ESTABILIDADE NUMÉRICA (N=50)
# ==============================================================================
# Adição de ruído infinitesimal para evitar matrizes singulares em amostras pequenas
np.random.seed(42)
data_fixed = data + np.random.normal(0, 0.00001, data.shape)

# ==============================================================================
# 4. TESTES DE ADEQUAÇÃO (KMO E BARTLETT)
# ==============================================================================
kmo_all, kmo_model = calculate_kmo(data_fixed)
chi_sq, p_value = calculate_bartlett_sphericity(data_fixed)

print("\n" + "="*50)
print("TESTES DE ADEQUAÇÃO DA AMOSTRA")
print("="*50)
print(f"Índice KMO Geral: {kmo_model:.3f}")
print(f"Teste de Bartlett (p-valor): {p_value:.5f}")
print("="*50 + "\n")

# ==============================================================================
# 5. GRÁFICO DE SEDIMENTAÇÃO (SCREE PLOT)
# ==============================================================================
# Extração inicial para verificar autovalores (eigenvalues)
fa_temp = FactorAnalyzer(n_factors=data_fixed.shape[1], rotation=None)
fa_temp.fit(data_fixed)
ev, v = fa_temp.get_eigenvalues()

plt.figure(figsize=(10, 6))
plt.scatter(range(1, data_fixed.shape[1] + 1), ev, color='red')
plt.plot(range(1, data_fixed.shape[1] + 1), ev, color='blue', linestyle='-')
plt.title('Gráfico de Sedimentação (Scree Plot)')
plt.xlabel('Número de Fatores')
plt.ylabel('Autovalor (Eigenvalue)')
plt.axhline(y=1, color='black', linestyle='--', label='Critério de Kaiser (Autovalor = 1)')
plt.grid(True, linestyle=':', alpha=0.6)
plt.legend()
plt.show()

# ==============================================================================
# 6. EXTRAÇÃO FINAL COM ROTAÇÃO VARIMAX
# ==============================================================================
# Definido 4 fatores com base na teoria e no Scree Plot
n_fatores = 4
fa_final = FactorAnalyzer(n_factors=n_fatores, rotation='varimax')
fa_final.fit(data_fixed)

# Criação da Tabela de Cargas Fatoriais
colunas_fatores = ['Coordenação', 'Cooperação', 'Colaboração', 'Representação']
loadings = pd.DataFrame(fa_final.loadings_,
                        index=existing_cols,
                        columns=colunas_fatores)

print("\n" + "="*50)
print("MATRIZ DE CARGAS FATORIAIS (ROTACIONADA)")
print("="*50)
print(loadings.round(3))
print("="*50)

# Variância Explicada
var_total = fa_final.get_factor_variance()
print(f"\nVariância Total Explicada Acumulada: {var_total[2][-1]*100:.2f}%")